In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/Job_Placement_Data.csv')

**ONE HOT ENCODING-USING PANDAS(PD.GET_DUMMIES**

In [ ]:
my_data={'color':['yellow','green','red','white']}

In [ ]:
type(my_data)

dict

In [ ]:
my_data_df=pd.DataFrame(my_data)

In [ ]:
type(my_data_df)

pandas.core.frame.DataFrame

In [ ]:
my_data_df=pd.get_dummies(my_data_df,dtype=int)

In [ ]:
my_data_df

   color_green  color_red  color_white  color_yellow
0            0          0            0             1
1            1          0            0             0
2            0          1            0             0
3            0          0            1             0

In [ ]:
df

,gender,ssc_percentage,ssc_board,hsc_percentage,hsc_board,hsc_subject,degree_percentage,undergrad_degree,work_experience,emp_test_percentage,specialisation,mba_percent,status
0,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed
1,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed
2,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed
3,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed
4,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed
211,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed
212,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed
213,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed
214,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed

In [ ]:
df.shape

(215, 13)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gender               215 non-null    object
 1   ssc_percentage       215 non-null    float64
 2   ssc_board            215 non-null    object
 3   hsc_percentage       215 non-null    float64
 4   hsc_board            215 non-null    object
 5   hsc_subject          215 non-null    object
 6   degree_percentage    215 non-null    float64
 7   undergrad_degree     215 non-null    object
 8   work_experience      215 non-null    object
 9   emp_test_percentage  215 non-null    float64
 10  specialisation       215 non-null    object
 11  mba_percent          215 non-null    float64
 12  status               215 non-null    object
dtypes: float64(5), object(8)
memory usage: 22.0+ KB

In [ ]:
df.isnull().sum()

gender                 0
ssc_percentage         0
ssc_board              0
hsc_percentage         0
hsc_board              0
hsc_subject            0
degree_percentage      0
undergrad_degree       0
work_experience        0
emp_test_percentage    0
specialisation         0
mba_percent            0
status                 0
dtype: int64

In [ ]:
df.describe()

,ssc_percentage,hsc_percentage,degree_percentage,emp_test_percentage,mba_percent
count,215.000000,215.000000,215.000000,215.000000,215.000000
mean,67.303395,66.333163,66.370186,72.100558,62.278186
std,10.827205,10.897509,7.358743,13.275956,5.833385
min,40.890000,37.000000,50.000000,50.000000,51.210000
25%,60.600000,60.900000,61.000000,60.000000,57.945000
50%,67.000000,65.000000,66.000000,71.000000,62.000000
75%,75.700000,73.000000,72.000000,83.500000,66.255000
max,89.400000,97.700000,91.000000,98.000000,77.890000

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.corr(numeric_only=True)

,ssc_percentage,hsc_percentage,degree_percentage,emp_test_percentage,mba_percent
ssc_percentage,1.000000,0.511472,0.538404,0.261993,0.388478
hsc_percentage,0.511472,1.000000,0.434206,0.245113,0.354823
degree_percentage,0.538404,0.434206,1.000000,0.224470,0.402364
emp_test_percentage,0.261993,0.245113,0.224470,1.000000,0.218055
mba_percent,0.388478,0.354823,0.402364,0.218055,1.000000

In [ ]:
df.value_counts('gender')

gender
M    139
F     76
Name: count, dtype: int64

In [ ]:
df.value_counts('ssc_board')

ssc_board
Central    116
Others      99
Name: count, dtype: int64

In [ ]:
df.value_counts('hsc_board')

hsc_board
Others     131
Central     84
Name: count, dtype: int64

In [ ]:
df.value_counts('hsc_subject')

hsc_subject
Commerce    113
Science      91
Arts         11
Name: count, dtype: int64

In [ ]:
df.value_counts('undergrad_degree')

undergrad_degree
Comm&Mgmt    145
Sci&Tech      59
Others        11
Name: count, dtype: int64

In [ ]:
df.value_counts('specialisation')

specialisation
Mkt&Fin    120
Mkt&HR      95
Name: count, dtype: int64

**ohe using get dummies**

In [ ]:
#df=pd.get_dummies(df,columns=['gender','ssc_board','hsc_board','hsc_subject','undergrad_degree','work_experience','specialisation'],dtype=int)

In [ ]:
df

,gender,ssc_percentage,ssc_board,hsc_percentage,hsc_board,hsc_subject,degree_percentage,undergrad_degree,work_experience,emp_test_percentage,specialisation,mba_percent,status
0,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed
1,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed
2,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed
3,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed
4,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed
211,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed
212,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed
213,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed
214,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed

**OHE using sklearn's ohe class**

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe=OneHotEncoder()

In [ ]:
df_to_encode=['gender','ssc_board','hsc_board','hsc_subject','undergrad_degree','work_experience','specialisation']

In [ ]:
encoded_df=ohe.fit_transform(df[df_to_encode]).toarray()

In [ ]:
encoded_df

array([[0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 1., ..., 1., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 1., 1., ..., 0., 0., 1.]])

In [ ]:
encoded_df.shape

(215, 16)

In [ ]:
encoded_df=pd.DataFrame(encoded_df,columns=ohe.get_feature_names_out(df_to_encode))

In [ ]:
type(encoded_df)

pandas.core.frame.DataFrame

In [ ]:
df=pd.concat([df,encoded_df],axis=1)

In [ ]:
df

,gender,ssc_percentage,ssc_board,hsc_percentage,hsc_board,hsc_subject,degree_percentage,undergrad_degree,work_experience,emp_test_percentage,...,hsc_subject_Arts,hsc_subject_Commerce,hsc_subject_Science,undergrad_degree_Comm&Mgmt,undergrad_degree_Others,undergrad_degree_Sci&Tech,work_experience_No,work_experience_Yes,specialisation_Mkt&Fin,specialisation_Mkt&HR
0,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
1,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
3,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
4,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
211,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
212,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
213,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
214,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0

In [ ]:
df.drop(df_to_encode,axis=1,inplace=True)

In [ ]:
df

,ssc_percentage,hsc_percentage,degree_percentage,emp_test_percentage,mba_percent,status,gender_F,gender_M,ssc_board_Central,ssc_board_Others,...,hsc_subject_Arts,hsc_subject_Commerce,hsc_subject_Science,undergrad_degree_Comm&Mgmt,undergrad_degree_Others,undergrad_degree_Sci&Tech,work_experience_No,work_experience_Yes,specialisation_Mkt&Fin,specialisation_Mkt&HR
0,67.00,91.00,58.00,55.0,58.80,Placed,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
1,79.33,78.33,77.48,86.5,66.28,Placed,0.0,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,65.00,68.00,64.00,75.0,57.80,Placed,0.0,1.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
3,56.00,52.00,52.00,66.0,59.43,Not Placed,0.0,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
4,85.80,73.60,73.30,96.8,55.50,Placed,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,80.60,82.00,77.60,91.0,74.49,Placed,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
211,58.00,60.00,72.00,74.0,53.62,Placed,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
212,67.00,67.00,73.00,59.0,69.72,Placed,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
213,74.00,66.00,58.00,70.0,60.23,Placed,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
214,62.00,58.00,53.00,89.0,60.22,Not Placed,0.0,1.0,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0

**lable encoding**

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:
df['status']=le.fit_transform(df['status'])

In [ ]:
df

,ssc_percentage,hsc_percentage,degree_percentage,emp_test_percentage,mba_percent,status,gender_F,gender_M,ssc_board_Central,ssc_board_Others,...,hsc_subject_Arts,hsc_subject_Commerce,hsc_subject_Science,undergrad_degree_Comm&Mgmt,undergrad_degree_Others,undergrad_degree_Sci&Tech,work_experience_No,work_experience_Yes,specialisation_Mkt&Fin,specialisation_Mkt&HR
0,67.00,91.00,58.00,55.0,58.80,1,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
1,79.33,78.33,77.48,86.5,66.28,1,0.0,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,65.00,68.00,64.00,75.0,57.80,1,0.0,1.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
3,56.00,52.00,52.00,66.0,59.43,0,0.0,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
4,85.80,73.60,73.30,96.8,55.50,1,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,80.60,82.00,77.60,91.0,74.49,1,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
211,58.00,60.00,72.00,74.0,53.62,1,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
212,67.00,67.00,73.00,59.0,69.72,1,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
213,74.00,66.00,58.00,70.0,60.23,1,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
214,62.00,58.00,53.00,89.0,60.22,0,0.0,1.0,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0

**Ordinal Encoding**

In [ ]:
odf=pd.DataFrame({'review':['average','poor','good','good','average'],'education':['school','ug','pg','pg','ug']})

In [ ]:
odf

    review education
0  average    school
1     poor        ug
2     good        pg
3     good        pg
4  average        ug

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
order_encode=OrdinalEncoder(categories=[['poor','average','good'],['school','ug','pg']])

In [ ]:
odf=order_encode.fit_transform(odf)

In [ ]:
odf=pd.DataFrame(odf,columns=order_encode.get_feature_names_out())

In [ ]:
odf

   review  education
0     1.0        0.0
1     0.0        1.0
2     2.0        2.0
3     2.0        2.0
4     1.0        1.0